spring:
  datasource:
    url: jdbc:sqlserver://192.168.3.253:1433;DatabaseName=qianerpgsp
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: web
    password: c18d3befb7f4433a
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        login-password: rootroot
        login-username: ydtDruidView
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
server:
  port: 8082
logging:
  file:
    max-size: 10MB
  path:
    ${default.logFolder}
  level:
    com.lan: info
default:
  password:
    '666'
  imageFolder:
    'D:\质检单\'
  logFolder:
    'D:/log/'